spring:
  output:
    ansi:
      enabled: ALWAYS
      console-available: true

redis:
  host: 192.168.99.100
  port: 6379

app:
  datasource:
    jdbcUrl: jdbc:mysql://192.168.99.100:3306/springboot_test?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
    pool-size: 30