CREATE TABLE IF NOT EXISTS person (
    id BINARY(16) NOT NULL PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    age TINYINT,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);